/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_merlab_signals_llm_loader_LlamaCppLoader */

#ifndef _Included_com_merlab_signals_llm_loader_LlamaCppLoader
#define _Included_com_merlab_signals_llm_loader_LlamaCppLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_merlab_signals_llm_loader_LlamaCppLoader
 * Method:    initModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_merlab_signals_llm_loader_LlamaCppLoader_initModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_merlab_signals_llm_loader_LlamaCppLoader
 * Method:    infer
 * Signature: (JLjava/lang/String;ID)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_merlab_signals_llm_loader_LlamaCppLoader_infer
  (JNIEnv *, jobject, jlong, jstring, jint, jdouble);

/*
 * Class:     com_merlab_signals_llm_loader_LlamaCppLoader
 * Method:    freeModel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_merlab_signals_llm_loader_LlamaCppLoader_freeModel
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
